/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mx_eglobal_JniOperacionesWrapper */

#ifndef _Included_com_mx_eglobal_JniOperacionesWrapper
#define _Included_com_mx_eglobal_JniOperacionesWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mx_eglobal_JniOperacionesWrapper
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mx_eglobal_JniOperacionesWrapper_load
  (JNIEnv *, jobject);

/*
 * Class:     com_mx_eglobal_JniOperacionesWrapper
 * Method:    media
 * Signature: ([II)F
 */
JNIEXPORT jfloat JNICALL Java_com_mx_eglobal_JniOperacionesWrapper_media
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_mx_eglobal_JniOperacionesWrapper
 * Method:    productoPunto
 * Signature: ([I[II)I
 */
JNIEXPORT jint JNICALL Java_com_mx_eglobal_JniOperacionesWrapper_productoPunto
  (JNIEnv *, jobject, jintArray, jintArray, jint);

/*
 * Class:     com_mx_eglobal_JniOperacionesWrapper
 * Method:    maxMin
 * Signature: ([II[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mx_eglobal_JniOperacionesWrapper_maxMin
  (JNIEnv *, jobject, jintArray, jint, jintArray);

/*
 * Class:     com_mx_eglobal_JniOperacionesWrapper
 * Method:    toMayusculas
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mx_eglobal_JniOperacionesWrapper_toMayusculas
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mx_eglobal_JniOperacionesWrapper
 * Method:    getSubLista
 * Signature: ([I[IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mx_eglobal_JniOperacionesWrapper_getSubLista
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
