/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mx_eglobal_JniCalculadoraWrapper */

#ifndef _Included_com_mx_eglobal_JniCalculadoraWrapper
#define _Included_com_mx_eglobal_JniCalculadoraWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mx_eglobal_JniCalculadoraWrapper
 * Method:    load
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mx_eglobal_JniCalculadoraWrapper_load
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mx_eglobal_JniCalculadoraWrapper
 * Method:    suma
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mx_eglobal_JniCalculadoraWrapper_suma
  (JNIEnv *, jobject);

/*
 * Class:     com_mx_eglobal_JniCalculadoraWrapper
 * Method:    resta
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mx_eglobal_JniCalculadoraWrapper_resta
  (JNIEnv *, jobject);

/*
 * Class:     com_mx_eglobal_JniCalculadoraWrapper
 * Method:    multiplica
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mx_eglobal_JniCalculadoraWrapper_multiplica
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
